import { LayoutMain } from "@/modules/core/layouts";
import type { Metadata } from "next";
import "@/modules/core/styles/index.css";

export const metadata: Metadata = {
  title: "Hechizos Culinarios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <LayoutMain>{children}</LayoutMain>
      </body>
    </html>
  );
}
