import { LayoutMain } from "@/modules/core/layouts";
import type { Metadata } from "next";
import "@/modules/core/styles/index.css";

export const metadata: Metadata = {
  title: "Hechizos Culinarios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="bg-purple-600 flex flex-col gap-14 justify-between min-h-screen">
        <LayoutMain>{children}</LayoutMain>
      </body>
    </html>
  );
}
